name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  built-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npx eslint .

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST with Default Rules
        run: semgrep --config=p/ci . --verbose --no-git-ignore

      - name: Verify code formatting
        run: npx prettier --check --write .

      - name: Generate Test Coverage Report
        run: npm test -- --coverage

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Run npm audit
        run: npm audit --audit-level=moderate

  docker-build-and-push:
    needs: built-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Image Tags
        run: |
          echo "IMAGE_TAG=ghcr.io/hassanmunir/crudapi-project:${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_TAG_LATEST=ghcr.io/hassanmunir/crudapi-project:latest" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .

      - name: Scan image
        uses: anchore/scan-action@v6
        with:
          image: "ghcr.io/hassanmunir/crudapi-project:latest"
          fail-build: false

      - uses: anchore/sbom-action@v0
        with:
          image: "ghcr.io/hassanmunir/crudapi-project:latest"

      - name: Push Docker Image to GHCR
        run: |
          docker push $IMAGE_TAG
          docker push $IMAGE_TAG_LATEST
